# Site settings
title: Che-Yi Liao
description: Personalized LLM, Constrained Alignment, AI-Driven Learning and Operations Management, AI in Healthcare
url: "https://CheYiLiao.github.io"
baseurl: ""

# Personal info
author:
  name: Che-Yi Liao
  email: cliao48 at gatech dot edu
  photo: /assets/images/profile.jpg

  # Primary position
  title: George Fellow | Seth Bonder Fellow
  dept: PhD Candidate, Machine Learning
  school: Georgia Institute of Technology
  # Leave blank or remove to disable links:

# Social links (leave blank or remove to hide)
social:
  google_scholar: "https://scholar.google.com/citations?user=qX9MI1MAAAAJ&hl=en"
  github: "https://github.com/CheYiLiao"
  linkedin: "https://linkedin.com/in/che-yi-liao"

# Build settings
markdown: kramdown
permalink: pretty
